//
//  song.h
//  
//
//  Created by Harrison Bronfeld on 6/6/17.
//
//

#ifndef song_h
#define song_h

#include "audio.h"

typedef struct {
    int size;
    notes_t notes[];
} songs_t;

void play_song(notes_t notes[], int size);

static songs_t HOT_CROSS_BUNS = {34, {{B4, QTR - STAC},
    {REST, STAC},
    {A4, QTR - STAC},
    {REST, STAC},
    {G4, HALF - STAC},
    {REST, STAC},
    {B4, QTR - STAC},
    {REST, STAC},
    {A4, QTR - STAC},
    {REST, STAC},
    {G4, HALF - STAC},
    {REST, STAC},
    {G4, EIT - STAC},
    {REST, STAC},
    {G4, EIT - STAC},
    {REST, STAC},
    {G4, EIT - STAC},
    {REST, STAC},
    {G4, EIT - STAC},
    {REST, STAC},
    {A4, EIT - STAC},
    {REST, STAC},
    {A4, EIT - STAC},
    {REST, STAC},
    {A4, EIT - STAC},
    {REST, STAC},
    {A4, EIT - STAC},
    {REST, STAC},
    {B4, QTR - STAC},
    {REST, STAC},
    {A4, QTR - STAC},
    {REST, STAC},
    {G4, HALF - STAC},
    {REST, STAC}}};

static songs_t TWINKLE_TWINKLE = {84, {{C4, QTR - STAC},
    {REST, STAC},
    {C4, QTR - STAC},
    {REST, STAC},
    {G4, QTR - STAC},
    {REST, STAC},
    {G4, QTR - STAC},
    {REST, STAC},
    {A4, QTR - STAC},
    {REST, STAC},
    {A4, QTR - STAC},
    {REST, STAC},
    {G4, HALF - STAC},
    {REST, STAC},
    {F4, QTR - STAC},
    {REST, STAC},
    {F4, QTR - STAC},
    {REST, STAC},
    {E4, QTR - STAC},
    {REST, STAC},
    {E4, QTR - STAC},
    {REST, STAC},
    {D4, QTR - STAC},
    {REST, STAC},
    {D4, QTR - STAC},
    {REST, STAC},
    {C4, HALF - STAC},
    {REST, STAC},
    {G4, QTR - STAC},
    {REST, STAC},
    {G4, QTR - STAC},
    {REST, STAC},
    {F4, QTR - STAC},
    {REST, STAC},
    {F4, QTR - STAC},
    {REST, STAC},
    {E4, QTR - STAC},
    {REST, STAC},
    {E4, QTR - STAC},
    {REST, STAC},
    {D4, HALF - STAC},
    {REST, STAC},
    {G4, QTR - STAC},
    {REST, STAC},
    {G4, QTR - STAC},
    {REST, STAC},
    {F4, QTR - STAC},
    {REST, STAC},
    {F4, QTR - STAC},
    {REST, STAC},
    {E4, QTR - STAC},
    {REST, STAC},
    {E4, QTR - STAC},
    {REST, STAC},
    {D4, HALF - STAC},
    {REST, STAC},
    {C4, QTR - STAC},
    {REST, STAC},
    {C4, QTR - STAC},
    {REST, STAC},
    {G4, QTR - STAC},
    {REST, STAC},
    {G4, QTR - STAC},
    {REST, STAC},
    {A4, QTR - STAC},
    {REST, STAC},
    {A4, QTR - STAC},
    {REST, STAC},
    {G4, HALF - STAC},
    {REST, STAC},
    {F4, QTR - STAC},
    {REST, STAC},
    {F4, QTR - STAC},
    {REST, STAC},
    {E4, QTR - STAC},
    {REST, STAC},
    {E4, QTR - STAC},
    {REST, STAC},
    {D4, QTR - STAC},
    {REST, STAC},
    {D4, QTR - STAC},
    {REST, STAC},
    {C4, HALF - STAC},
    {REST, STAC}}};


//#ABDE
static songs_t FIREWORKS = {100, {{C3, EIT},
    {C3, EIT},
    {E3, EIT},
    {C3, EIT},
    {C3, QTR},
    {REST, QTR},
    {A3, EIT},
    {B3, EIT},
    {B3, EIT},
    {A3, EIT},
    {A3, HALF},
    {A3, EIT},
    {B3, EIT},
    {B3, EIT},
    {A3, EIT},
    {A3, QTR},
    {REST, EIT},
    {A3, EIT},
    {A3, EIT},
    {A3, EIT},
    {B3, EIT},
    {C3, EIT},
    {C3, QTR},
    {REST, QTR},
    {C3, EIT},
    {E4, EIT},
    {E4, EIT},
    {C3, EIT},
    {C3, QTR},
    {REST, QTR},
    {A3, EIT},
    {B3, EIT},
    {B3, EIT},
    {A3, EIT},
    {A3, HALF},
    {A3, EIT},
    {B3, EIT},
    {B3, EIT},
    {A3, EIT},
    {A3, QTR},
    {A3, EIT},
    {A3, EIT},
    {A3, EIT},
    {A3, EIT},
    {B4, EIT},
    {C4, EIT},
    {C4s, EIT},
    {C4, EIT},
    {REST, EIT},
    {E3, EIT},
    {E3, EIT},
    {A3, EIT},
    {A3, EIT},
    {E3, EIT},
    {E3, QTR},
    {REST, EIT},
    {E3, EIT},
    {E3, EIT},
    {E3, EIT},
    {F3, EIT},
    {A3, QTR},
    {A3, QTR},
    {REST, QTR},
    {E3, EIT},
    {A3, EIT},
    {A3, EIT},
    {E3, EIT},
    {E3, EIT},
    {E3, EIT},
    {F3, EIT},
    {E3, EIT},
    {E3, EIT},
    {C3, EIT},
    {F3, EIT},
    {E3, EIT},
    {E3, HALF},
    {C3, EIT},
    {E3, EIT},
    {E3, EIT},
    {C3, EIT},
    {C3, QTR}}}; //17

static songs_t SCALE = {14, {{C4, HALF},
    {D4, QTR},
    {E4, QTR},
    {F4, QTR},
    {G4, QTR},
    {A4, QTR},
    {B4, QTR},
    {C5, HALF},
    {B4, QTR},
    {A4, QTR},
    {G4, QTR},
    {F4, QTR},
    {E4, QTR},
    {D4, QTR}}};
    
    
    
    

#endif /* song_h */
