//
//  song.h
//  
//
//  Created by Harrison Bronfeld on 6/6/17.
//
//

#ifndef song_h
#define song_h

#include "audio.h"

typedef struct {
    int size;
    notes_t notes[];
} songs_t;

void play_song(notes_t notes[], int size);

static songs_t HOT_CROSS_BUNS = {34, {{B4, QTR - STAC},
    {REST, STAC},
    {A4, QTR - STAC},
    {REST, STAC},
    {G4, HALF - STAC},
    {REST, STAC},
    {B4, QTR - STAC},
    {REST, STAC},
    {A4, QTR - STAC},
    {REST, STAC},
    {G4, HALF - STAC},
    {REST, STAC},
    {G4, EIT - STAC},
    {REST, STAC},
    {G4, EIT - STAC},
    {REST, STAC},
    {G4, EIT - STAC},
    {REST, STAC},
    {G4, EIT - STAC},
    {REST, STAC},
    {A4, EIT - STAC},
    {REST, STAC},
    {A4, EIT - STAC},
    {REST, STAC},
    {A4, EIT - STAC},
    {REST, STAC},
    {A4, EIT - STAC},
    {REST, STAC},
    {B4, QTR - STAC},
    {REST, STAC},
    {A4, QTR - STAC},
    {REST, STAC},
    {G4, HALF - STAC},
    {REST, STAC}}};

static songs_t TWINKLE_TWINKLE = {83, {{C4, QTR - STAC},
    {REST, STAC},
    {C4, QTR - STAC},
    {REST, STAC},
    {G4, QTR - STAC},
    {REST, STAC},
    {G4, QTR - STAC},
    {REST, STAC},
    {A4, QTR - STAC},
    {REST, STAC},
    {A4, QTR - STAC},
    {REST, STAC},
    {G4, HALF - STAC},
    {REST, STAC},
    {F4, QTR - STAC},
    {REST, STAC},
    {F4, QTR - STAC},
    {REST, STAC},
    {E4, QTR - STAC},
    {REST, STAC},
    {E4, QTR - STAC},
    {REST, STAC},
    {D4, QTR - STAC},
    {REST, STAC},
    {D4, QTR - STAC},
    {REST, STAC},
    {C4, HALF - STAC},
    {REST, STAC},
    {G4, QTR - STAC},
    {REST, STAC},
    {G4, QTR - STAC},
    {REST, STAC},
    {F4, QTR - STAC},
    {REST, STAC},
    {F4, QTR - STAC},
    {REST, STAC},
    {E4, QTR - STAC},
    {REST, STAC},
    {E4, QTR - STAC},
    {REST, STAC},
    {D4, HALF - STAC},
    {REST, STAC},
    {G4, QTR - STAC},
    {REST, STAC},
    {G4, QTR - STAC},
    {REST, STAC},
    {F4, QTR - STAC},
    {REST, STAC},
    {F4, QTR - STAC},
    {REST, STAC},
    {E4, QTR - STAC},
    {REST, STAC},
    {E4, QTR - STAC},
    {REST, STAC},
    {D4, HALF - STAC},
    {REST, STAC},
    {C4, QTR - STAC},
    {REST, STAC},
    {C4, QTR - STAC},
    {REST, STAC},
    {G4, QTR - STAC},
    {REST, STAC},
    {G4, QTR - STAC},
    {REST, STAC},
    {A4, QTR - STAC},
    {REST, STAC},
    {A4, QTR - STAC},
    {REST, STAC},
    {G4, HALF - STAC},
    {REST, STAC},
    {F4, QTR - STAC},
    {REST, STAC},
    {F4, QTR - STAC},
    {REST, STAC},
    {E4, QTR - STAC},
    {REST, STAC},
    {E4, QTR - STAC},
    {REST, STAC},
    {D4, QTR - STAC},
    {REST, STAC},
    {D4, QTR - STAC},
    {REST, STAC},
    {C4, HALF - STAC},
    }};


//#ABDE
static songs_t HERE_COMES_THE_SUN = {48, {{REST, QTR},
    {C4s, EIT - STAC},
    {REST, STAC},
    {A3, EIT - STAC},
    {REST, STAC},
    {B3, EIT - STAC},
    {REST, STAC},
    {C4s, QTR - STAC},
    {REST, STAC},
    {A3, EIT},
    {A3, QTR - STAC},
    {REST, STAC},
    {C4s, EIT - STAC},
    {REST, STAC},
    {B3, EIT},
    {B3, EIT - STAC},
    {REST, STAC},
    {A3, QTR - STAC},
    {REST, STAC},
    {F3s, EIT},
    {F3s, EIT - STAC},
    {REST, STAC},
    {A3, QTR - STAC},
    {REST, STAC},
    {B3, EIT},
    {B3, EIT - STAC},
    {REST, STAC},
    {A3, QTR - STAC},
    {REST, STAC},
    {F3s, EIT - STAC},
    {REST, STAC},
    {G3s, EIT - STAC},
    {REST, STAC},
    {F3s, EIT - STAC},
    {REST, STAC},
    {G3s, EIT - STAC},
    {REST, STAC},
    {A3, EIT},
    {A3, EIT - STAC},
    {REST, STAC},
    {B3, QTR},
    {B3, EIT - STAC},
    {REST, STAC},
    {REST, QTR},
    {C4s, EIT - STAC},
    {REST, STAC},
    {A3, EIT - STAC},
    {REST, STAC},
    {B3, EIT - STAC},
    {REST, STAC},
    {C4s, QTR - STAC},
    {REST, STAC},
    {A3, EIT},
    {REST, STAC},
    
    
    
    
    }}; //17

static songs_t SCALE = {14, {{C4, HALF},
    {D4, QTR},
    {E4, QTR},
    {F4, QTR},
    {G4, QTR},
    {A4, QTR},
    {B4, QTR},
    {C5, HALF},
    {B4, QTR},
    {A4, QTR},
    {G4, QTR},
    {F4, QTR},
    {E4, QTR},
    {D4, QTR}}};
    
    
    
    

#endif /* song_h */
